# Read the Docs configuration file for Sphinx
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # Install uv
    - pip install uv>=0.9
    # Install the project and docs dependencies using uv
    - uv sync --group docs
    # Build HTML documentation with Sphinx (-c specifies config dir)
    - uv run sphinx-build -b html -c docs docs/source $READTHEDOCS_OUTPUT/html
